services:
  gateway:
    container_name: gateway
    build: ./gateway
    restart: always
    env_file:
      - gateway.env
    expose:
      - $PORTGAT
    ports:
      - $PORTGAT:$PORTGAT
    depends_on:
      - postgres
      - mlservices
      - rulesservices
      - redis
    networks:
      - cloudwalk_network

  mlservices:
    container_name: mlservices
    build: ./ml-service
    restart: always
    env_file:
      - mlservices.env
    expose:
      - $MLPORT
    networks:
      - cloudwalk_network
  
  rulesservices:
    container_name: rulesservices
    build: ./rules-service
    restart: always
    env_file:
      - rules.env
    expose:
      - $RULESPORT
    depends_on:
      - postgres
      - redis
    networks:
      - cloudwalk_network

  postgres:
    container_name: postgres
    image: postgres
    expose:
      - $POSTGRESPORT
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - cloudwalk_network

  redis:
    container_name: redis
    image: redis
    expose:
      - $REDISPORT
    env_file:
      - .env
    depends_on:
      - mlservices
    networks:
      - cloudwalk_network

networks:
  cloudwalk_network: