services:
  anti-fraud:
    container_name: anti-fraud
    build: .
    restart: always
    env_file:
     - .env
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
      - ml-services
    networks:
      - cloudwalk_network

  ml-services:
    container_name: ml-services
    build: .
    restart: always
    env_file:
     - .env
    expose:
      - 8888
    networks:
    - cloudwalk_network

  postgres:
    image: postgres
    expose:
      - $BDPORT
    ports:
      - $BDPORT:$BDPORT
    env_file:
     - .env
    networks:
      - cloudwalk_network
