services:
  anti-fraud:
    container_name: anti-fraud
    build: Dockerfile.ts
    restart: always
    env_file:
     - .env
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres

  ml:
    container_name: ml
    build: Dockerfile.py
    restart: always
    env_file:
     - .env
    expose:
      - $MLPORT
    ports:
      - $MLPORT:$MLPORT

  postgres:
    image: postgres
    env_file:
     - .env