services:
  magicsports-back:
    container_name: magicsports-back
    build: .
    restart: always
    env_file:
     - .env
    expose:
      - $PORT
    ports:
      - $PORT:$PORT
    depends_on:
      - mongodb

  postgres:
    image: postgres
    env_file:
     - .env