default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/devdb

test:
  <<: *default
  database: db/testdb

production:
  <<: *default
  database: db/clouddb
