name: Push Main Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: cd gateway/docker/test/ &&  echo "${{ secrets.ENV_FILE_TEST }}" > .env
      - name: Test
        run: cd gateway && npm run test
